apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-ingress
  namespace: netflix-dev
  labels:
    app: netflix-web
    environment: dev
  annotations:
    # Use staging issuer for dev (no rate limits, untrusted cert)
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dev.adedayo.shop
      secretName: dev-adedayo-shop-tls
  rules:
    - host: dev.adedayo.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netflix-web-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: netflix-api-service
                port:
                  number: 80
