apiVersion: v1
kind: Service
metadata:
  name: netflix-web-service
  namespace: netflix-dev
  labels:
    app: netflix-web
    environment: dev
spec:
  selector:
    app: netflix-web
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-api-service
  namespace: netflix-dev
  labels:
    app: netflix-api
    environment: dev
spec:
  selector:
    app: netflix-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
