# checkov:skip=CKV_K8S_21=Base template; namespace is applied per-environment at deploy time
apiVersion: v1
kind: ConfigMap
metadata:
  name: netflix-app-config
  namespace: netflix-dev
  labels:
    app: netflix-web
data:
  NGINX_PORT: "80"
  APP_NAME: "Netflix Streaming App"
